---
title: "R Notebook"
author: "Kevin Stachelek"
output:
  html_document:
    df_print: paged
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

# load packages

```{r load-lib}
library(Seurat)
library(tidyverse)
library(rprojroot)
library(fs)
library(scClustViz)
library(reticulate)
library(glue)
library(seuratTools)
proj_dir = rprojroot::find_root(criterion = has_file_pattern("*.Rproj"))
features <- c("gene", "transcript")
```


```{r}

features <- c("gene", "transcript")
sce_dir <- fs::path(proj_dir, "output", "sce")

seu_paths <- sce_dir %>% 
  dir_ls() %>% 
  path_filter("*_seu.rds") %>%
  identity()

feature_seus <- map(seu_paths, readRDS)
names(feature_seus) = c("gene", "transcript")


```

# run processing and clustering at different resolutions

```{r}

feature_seus <- map(feature_seus, seuratTools::seurat_pipeline, resolution = seq(0.2, 2.0, by = 0.2))

features <- c("gene", "transcript")
sce_dir <- fs::path(proj_dir, "output", "sce")

seu_paths <- fs::path(sce_dir, paste0(features, "_seu.rds"))

map2(feature_seus, seu_paths, saveRDS)

```

## load seurat objects

```{r}
sce_dir <- fs::path(proj_dir, "output", "sce")
seu_paths <- fs::path(sce_dir, paste0(features, "_seu.rds"))

feature_seus <- map(seu_paths, readRDS)
names(feature_seus) = c("gene", "transcript")

```

# add cell cycle scoring to seurat objects

```{r}
feature_seus <- seuratTools::annotate_cell_cycle(feature_seus)
```

# add marker genes to seurat objects 

```{r}
feature_seus <- map(feature_seus, seuratTools::find_all_markers)
```

# annotate low read count category in seurat metadata

```{r}
feature_seus <- map(feature_seus, seuratTools::add_read_count_col)
```

# Prep scclustviz data

```{r}

scclust_res_dir <- fs::path(proj_dir, "results", "scclustviz")

fs::dir_create(scclust_res_dir)

prep_scclust_viz <- function(seu, feature_type, assayType = "integrated") {
  # browser()
  cluster_names <- paste0("clusters_", seq(0.6, 1.0, by = 0.2))
  
  your_cluster_results <- getMD(seu)[,cluster_names]
  
  scclust_res_path <- fs::path(scclust_res_dir, paste0(feature_type, "_for_scClustViz.RData"))
  
  scvres <- CalcAllSCV(seu, your_cluster_results, assayType = assayType, exponent = exp(1), testAll = FALSE)
  
  save(seu, scvres, file = scclust_res_path)
  
  print(glue("saved output to {scclust_res_path}"))
  return(NULL)
  
}

purrr::imap(feature_seus, prep_scclust_viz, assayType = "RNA")

# runShiny(filePath="../results/scclustviz/for_scClustViz.RData")

```

