---
title: "R Notebook"
author: "Kevin Stachelek"
output: html_notebook
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```



```{r}
library('tidyverse')
library('fs')
library('rprojroot')
library(plotly)
proj_dir = rprojroot::find_root(criterion = has_file_pattern("*.Rproj"))
features = c("gene", "transcript")
```

## collate hisat2 qc from all 4 experiments

```{r, eval = F}
projs <- c("FACS_20170407_dshayler_H_sapiens_proj", "FACS_20171031_dshayler_H_sapiens_proj", "FACS_20181001_dshayler_H_sapiens_fetal_proj", "C1_20151130_HS_H_sapiens_proj")

hisat2_qc_paths <- path("~/single_cell_projects/quicklinks/", projs, "output", "multiqc_data", "multiqc_hisat2.txt") %>% 
  set_names(projs)

hisat2_qcs <- map(hisat2_qc_paths, read_tsv)

hisat2_qcs <- map(hisat2_qcs, ~mutate(.x, Sample = gsub(".his.*", "", Sample)))

hisat2_qcs[[2]] <- hisat2_qcs[[2]] %>% 
  mutate(sample_number = gsub(".*_S", "", Sample)) %>% 
  mutate(Sample = str_pad(sample_number, max(nchar(sample_number)), pad = "0")) 

hisat2_qcs[[3]] <- hisat2_qcs[[3]] %>% 
  mutate(sample_number = gsub(".*_S", "", Sample)) %>% 
  mutate(Sample = str_pad(sample_number, max(nchar(sample_number)), pad = "0"))

# correct lane specific alignments in 2018 data
hisat2_qcs[[3]] <- dplyr::mutate(hisat2_qcs[[3]], Sample = str_extract(Sample, "^[:digit:]+")) %>% 
  group_by(Sample) %>% 
  select(-sample_number) %>% 
  dplyr::summarise_all(.funs = sum) %>%
  identity()

expids <- c("ds20170407_S", "ds20171031_S", "ds20181001_S", "hs20151130_S")

hisat2_qcs <- map2(hisat2_qcs, expids, ~dplyr::mutate(.x, Sample = paste0(.y, Sample)))

aggregate_qc <- dplyr::bind_rows(hisat2_qcs)

write_csv(aggregate_qc, "~/single_cell_projects/quicklinks/4_seq_dshayler_w_organoid_HS_proj/results/aggregate_qc.csv")
```

```{r}
aggregate_qc <- read_csv("~/single_cell_projects/quicklinks/4_seq_dshayler_w_organoid_HS_proj/results/aggregate_qc.csv")
```


## load unfiltered seurat objects

```{r}
unfiltered_feature_seus_paths <- path(proj_dir, "output", "sce", paste0(features, "_seu.rds"))

unfiltered_seus <- map(unfiltered_feature_seus_paths, readRDS)

seu_cells <- map(unfiltered_seus, colnames)

low_read_count_cells <- colnames(unfiltered_seus[[1]][,unfiltered_seus[[1]]$read_count == "low_read_count"])
```


## clean hisat2 qc 

```{r}
align_cols <- c("overall_alignment_rate", "paired_aligned_none", "paired_aligned_discord_one", "paired_total", "paired_aligned_multi", "paired_aligned_one")

agg_qc_wo_na <- aggregate_qc %>% select(which(colMeans(is.na(.)) < 0.05)) %>%
  group_by(Sample) %>% 
  dplyr::arrange(desc(paired_total)) %>% 
  select(-overall_alignment_rate) %>% 
  tidyr::gather("align_type", "count", one_of(align_cols)) %>% 
  arrange(Sample, align_type) %>% 
  filter(Sample %in% seu_cells[[1]]) %>% 
  dplyr::mutate(read_count = ifelse(Sample %in% low_read_count_cells, "low_read_count", "keep")) %>% 
  identity()
```

# load filtered seurat obects

```{r}
feature_seus_ps <- path(proj_dir, "output", "sce", paste0(features, "_seu_remove_lowrc.rds")) 

feature_seus <- map(feature_seus_ps, readRDS)
```

```{r}
qc_samples <- dplyr::filter(agg_qc_wo_na, align_type == "paired_total") %>%
  pull(Sample)

thresholded_cells <- qc_samples[!qc_samples %in% colnames(feature_seus[[1]])]

```


## plot hisat2 results

```{r}
# agg_qc_wo_na <- dplyr::filter(agg_qc_wo_na, align_type == "paired_aligned_one")

p <- ggplot(agg_qc_wo_na, aes(x=reorder(Sample, -count), y = count, fill = read_count)) +
    scale_y_continuous(breaks = seq(0, 8e7, by = 5e5)) +
    geom_bar(position = "identity", stat = "identity") + 
    # geom_text(data=subset(agg_qc_wo_na, Sample %in% thresholded_cells & align_type == "paired_total"),
    #   aes(Sample, count, label=Sample)) +
    # geom_text(data=subset(agg_qc_wo_na, Sample %in% low_read_count_cells & align_type == "paired_aligned_one"),
    #   aes(Sample, count, label=Sample)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + 
  # scale_fill_manual(values = c( "low_read_count"="tomato", "keep"="gray" ), guide = FALSE ) + 
  labs(title = "Paired Aligned One Reads", x = "Sample") + 
  NULL

ggsave("~/single_cell_projects/quicklinks/4_seq_dshayler_w_organoid_HS_proj/results/aggregate_qc.pdf", p)
```

```{r}
agg_qc_wo_na0 <- colSums(as.matrix(unfiltered_seus[[1]]@assays$RNA@counts)) %>% 
  enframe() %>% 
  mutate(Sample = name, align_type = "paired_aligned_one", count = value) %>% 
  dplyr::mutate(read_count = ifelse(Sample %in% low_read_count_cells, "low_read_count", "keep")) %>% 
  identity()

p0 <- ggplot(agg_qc_wo_na, aes(x=reorder(Sample, -count), y = count, fill = read_count)) +
    # scale_y_continuous(breaks = seq(0, 8e7, by = 5e5)) +
    scale_y_log10() +
    geom_bar(position = "identity", stat = "identity") + 
    # geom_text(data=subset(agg_qc_wo_na, Sample %in% thresholded_cells & align_type == "paired_total"),
    #   aes(Sample, count, label=Sample)) +
    # geom_text(data=subset(agg_qc_wo_na, Sample %in% low_read_count_cells & align_type == "paired_aligned_one"),
    #   aes(Sample, count, label=Sample)) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + 
  scale_fill_manual(values = c( "low_read_count"="tomato", "keep"="gray" ), guide = FALSE ) + 
  labs(title = "Paired Aligned One Reads", x = "Sample") + 
  NULL
  
p0 <- ggplotly(p0)

# lowrc_path <- path(proj_dir, "results", "low_read_count_cells_dshayler_hsingh.html")

# htmlwidgets::saveWidget(as_widget(p), lowrc_path)

```

```{r}
p <- ggplotly(p)

lowrc_path <- path(proj_dir, "results", "low_read_count_cells_dshayler_hsingh.html")

htmlwidgets::saveWidget(as_widget(p), lowrc_path)

```

## find low read count cells

```{r}
agg_qc_wide <- tidyr::spread(agg_qc_wo_na, align_type, count)

low_read_count_cells <- dplyr::filter(agg_qc_wide, paired_total > 1e4) %>% 
  tidyr::gather("align_type", "count", one_of(align_cols)) %>%
  identity()
  
```


