---
title: "genes_detected_mean_total.Rmd"
author: "Kevin Stachelek"
date: "6/12/2018"
output:
  pdf_document: 
    latex_engine: xelatex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 1, echo=FALSE}
library(ggplot2)

#SHL 20170407
transcript_counts <- "~/single_cell_pipeline/output/FACS_20170407_sunlee_H_sapiens_output/transcript_count_matrix.csv"
gene_counts <- "~/single_cell_pipeline/output/FACS_20170407_sunlee_H_sapiens_output/gene_count_matrix.csv"

plot_features <- function(feature_counts){
  counts <- read.csv(feature_counts)
  rownames(counts) <- counts[,1]
  counts <- counts[,-1]
  
  features_det <- colSums(counts > 1)
  meanx <- mean(features_det)
  medx <- median(features_det)
  totalx <- sum(rowSums(counts) > 1) 
  
  features_plot <- ggplot() + aes(features_det) + 
    geom_density() +
     geom_vline(xintercept=meanx) +
      geom_vline(xintercept=medx, color='#FFFFFF')
  
  print(features_plot)
  
  print(paste0("median: ", medx, " mean: ", meanx, " total: ", totalx))  
}


```

## Transcript Counts SHL 20170407

```{r 2, echo=FALSE}
plot_features(transcript_counts)
```

## Gene Counts SHL 20170407

```{r 3, echo=FALSE}
plot_features(gene_counts)
```

## Transcript Counts SHL 20171031
```{r 4, echo=FALSE}

transcript_counts <- "~/single_cell_pipeline/output/FACS_20171031_sunlee_H_sapiens_output/transcript_count_matrix.csv"
gene_counts <- "~/single_cell_pipeline/output/FACS_20171031_sunlee_H_sapiens_output/gene_count_matrix.csv"
plot_features(transcript_counts)
```

## Gene Counts SHL 20171031

```{r 5, echo=FALSE}
plot_features(gene_counts)
```