---
title: "H. Singh Mouse Datasets"
author: "Mitali Singh"
output: html_document
---

```{r, echo = F}
knitr::opts_chunk$set(echo = F, message = F)
```


# load required libraries 

```{r}
library(SingleCellExperiment)
library(tidyverse)
library(glue)
library(rprojroot)
proj_dir = find_root_file(criterion = ".Rhistory")
```


# Load functions

```{r}

append_expids <- function(txi, tpm_meta, expid){
	
	
	tpm_ids <- colnames(txi$counts)
	meta_ids <- tpm_meta[[1]]
	
	# tpm_ids <- str_replace_all(tpm_ids, "[[:alpha:]]", "")
	# meta_ids <- str_replace_all(meta_ids, "[[:alpha:]]", "")
	
	tpm_ids <- as.character(glue::glue("{expid}_{tpm_ids}"))
	meta_ids <- as.character(glue::glue("{expid}_{meta_ids}"))
	
	colnames(txi$counts) <- tpm_ids
	colnames(txi$abundance) <- tpm_ids
	colnames(txi$length) <- tpm_ids
	tpm_meta[,1] <- meta_ids
	
	return(list("txi" = txi, "colData" = tpm_meta))
}

mergeSingleCellExperiments <- function(sce1, sce2, expids){
	# browser()
	
	# check that features (genes or transcripts) are idential between sces
	identical(rownames(sce1), rownames(sce2))
	
	#	Now we’ll check that there aren’t any repeated cellIDs:
	
	sum(colnames(sce1) %in% colnames(sce2))
	
	#	Everything is ok, so we can go ahead and combine them:
	
	sample_ids <- c(colnames(sce1), colnames(sce2))
	
	cd1 <- data.frame(colData(sce1)) %>% 
		dplyr::select(-batch)
	cd2 <- data.frame(colData(sce2)) %>% 
		dplyr::select(-batch)
	
	merge_cd <- dplyr::bind_rows(cd1, cd2, .id = "batch")
	
	rownames(merge_cd) <- sample_ids
	if(!"Sample_ID" %in% colnames(merge_cd)){
		merge_cd <- cbind(Sample_ID = rownames(merge_cd), merge_cd)
	}
	
	# merge counts
	
	assay_names <- intersect(names(assays(sce1)), names(assays(sce2)))
	
	assays <- purrr::map(assay_names, merge_assay, sce1, sce2)
	names(assays) <- assay_names
	
	merge_rd <- data.frame(row.names = rownames(assays$counts), "features" = rownames(assays$counts))
	
	merge_sce <- SingleCellExperiment(assays=list(assays), colData=merge_cd, rowData=merge_rd)
	
	return(merge_sce)
}

merge_assay <- function(assay_name, sce1, sce2){
	  tbl1 <- as_tibble(assays(sce1)[[assay_name]], rownames = "feature")
		tbl2 <- as_tibble(assays(sce2)[[assay_name]], rownames = "feature")
		merge_assay <- dplyr::inner_join(tbl1, tbl2, by = "feature") %>% 
    na.omit() %>% 
    tibble::column_to_rownames("feature") %>% 
			as.matrix()
		
		return(merge_assay)
	}

```

```{r}

proj_1 <- "~/single_cell_projects/quicklinks/FACS_20170407_sunlee_H_sapiens_proj/"
proj_2 <- "~/single_cell_projects/quicklinks/FACS_20171031_sunlee_H_sapiens_proj/"

projects <- c(proj_1, proj_2)

gene_sce_fs <- paste0(projects, "output/sce/gene_sce.rds")
transcript_sce_fs <- paste0(projects, "output/sce/transcript_sce.rds")

gene_sces <- purrr::map(gene_sce_fs, readRDS)
transcript_sces <- purrr::map(transcript_sce_fs, readRDS)

expids <- c("shl20170407", "shl20171031")

```


```{r}
# merge sces from different batches
output_dir <- fs::path(proj_dir, "output" , "sce")
dir.create(output_dir)
gene_sce <- purrr::reduce(gene_sces, mergeSingleCellExperiments, expids)
transcript_sce <- purrr::reduce(transcript_sces, mergeSingleCellExperiments, expids)

batch_samples <- lapply(gene_sces, colnames)
names(batch_samples) <- expids

batch_mutate <- function(sce, batch_samples){

		sce <- scater::mutate(sce, batch = case_when(colData(sce)$Sample_ID %in% batch_samples[[1]] ~ names(batch_samples)[[1]],
																											 colData(sce)$Sample_ID %in% batch_samples[[2]] ~ names(batch_samples)[[2]]))
}

gene_sce <- batch_mutate(gene_sce, batch_samples)
transcript_sce <- batch_mutate(transcript_sce, batch_samples)

features = c("gene", "transcript")
feature_sces <- list("gene" = gene_sce, "transcript" = transcript_sce)
```
```

```{r}
sce_files = paste0(features, "_sce_", paste0(expids, collapse = "_"), ".rds")

sce_paths <- fs::path(proj_dir, "output", "sce", sce_files)

purrr::map2(feature_sces, sce_paths, saveRDS)
```

