---
title: "scclust_tutorial.Rmd"
author: "Kevin Stachelek"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r , include=FALSE}
library(stchlk.notes)
pwd <- getwd()
stchlk.notes::loadkey(pwd)


library(SCclust)
library(futile.logger)
flog.threshold(ERROR)
```


```{r}
#fix error in chrom_numeric function 
is.number <- is.numeric

gc_df <- read.csv("T10data/hg19_R50_B20k_bins_boundaries.txt",
header = T, sep='\t')
gc_df$chrom.numeric <- chrom_numeric(gc_df$bin.chrom)
```

```{r}
cytobands <- read.csv("T10data/cytoBand.txt", header = F, sep='\t')
```

```{r}
centroareas <- calc_centroareas(cytobands, centromere=c("p11", "q11"))
```


```{r}
centrobins <- calc_regions2bins(gc_df, centroareas)
length(centrobins)
```

```{r}
gc_df <- gc_df[-centrobins, ]
dim(gc_df)
```

# collect varbin files for all samples 

```{r}
varbin_files <- varbin_input_files("T10data/varbin", "*.varbin.20k.txt")
```

## use subset for tutorial 

```{r}
varbin_files <- varbin_files[seq(10),]
dim(varbin_files)
```


```{r}
res <- segment_varbin_files(varbin_files, gc_df, centrobins)
```

```{r}
filenames <- case_filenames("T10data/results", "NavinT10")
save_table(filenames$seg, res$seg)
save_table(filenames$ratio, res$ratio)
```

```{r}
cells <- uber_cells(res$seg)$cells
save_table(filenames$cells, data.frame(cell=cells))
```

```{r}
ploidies_df <- calc_ploidies(gc_df, res$seg)
```

```{r}
pins <- calc_pinmat(gc_df, res$seg, dropareas=centroareas)
pinmat_df <- pins$pinmat
pins_df <- pins$pins
save_table(filenames$featuremat, pinmat_df)
save_table(filenames$features, pins_df)
```

```{r}
fisher <- sim_fisher_wrapper(
pinmat_df, pins_df, njobs=30, nsim=150, nsweep=10)
true_pv <- fisher$true
sim_pv <- fisher$sim
```

```{r}
save_mat(filenames$true_pv, true_pv)
save_mat(filenames$sim_pv, sim_pv)
```

```{r}
# devtools::load_all()
# flog.threshold(DEBUG)
mfdr <- fisher_fdr(true_pv, sim_pv, cells)
mfdr[1:5,1:5]

mdist <- fisher_dist(true_pv, cells)
mdist[1:5,1:5]
```

```{r}
hc <- hclust_tree(pinmat_df, mfdr, mdist,hcmethod='average')
names(hc)

plot(hc)

tree_df <- tree_py(mdist, method='average')
head(tree_df)
```

```{r}
save_table(filenames$tree, tree_df)
```

```{r}
hc <- find_clones(hc)

hc$softclones
```

```{r}
subclones <- find_subclones(hc, pinmat_df, pins_df, nsim=nsim)

save_table(filenames$clone, subclones)
```
















