---
title: "R Notebook"
output: html_notebook
---

```{r, echo = F}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```


```{r load-lib}

# load libraries ----------------------------------------------------------
library(tidyverse)
library(msigdbr)
library(clusterProfiler)
library(fgsea)
library(tximport)
library(annotables)
```

```{r load-func}

scde_feature_list <- function(feature_df){
	feature_df <- dplyr::mutate(feature_df, fcSign = sign(mle)) %>% 
		dplyr::mutate(rank = -log10(cZ)/fcSign) %>% 
		dplyr::select(symbol, rank)
	
	feature_df <- feature_df[complete.cases(feature_df),]
	
	ranked_list <- feature_df[["rank"]]
	names(ranked_list) <- feature_df[["symbol"]]
	return(ranked_list)
}

edger_feature_list <- function(feature_df){
	browser()
	
	feature_df  <- tibble::rownames_to_column(feature_df, var = "symbol")
	
	feature_df <- dplyr::mutate(feature_df, fcSign = sign(logFC)) %>% 
		dplyr::mutate(rank = -log10(FDR)/fcSign) %>%
		# dplyr::left_join(grch38_tx2gene, by = "enstxp") %>% 
		# dplyr::left_join(grch38, by = "ensgene") %>% 
		dplyr::select(symbol, rank) %>%
		identity()
	
	feature_df <- feature_df[complete.cases(feature_df),]
	
	ranked_list <- feature_df[["rank"]]
	names(ranked_list) <- feature_df[["symbol"]]
	return(ranked_list)
}

```


```{r load-ref}



# load reference ---------------------------------------------------------------
m_df = msigdbr(species = "Homo sapiens")

m_t2g = m_df %>% 
	dplyr::select(gs_name, entrez_gene) %>% 
	as.data.frame()
```

```{r load-dat}

# load data ---------------------------------------------------------------

shl_data <- read_csv("~/single_cell_projects/quicklinks/FACS_20170407_sunlee_H_sapiens_proj/output/scde/transcript/20181025_PT1_scde_shCtrl_vs_shRB1-LatePT1.csv")

ks_data <- top$table
```

```{r}


# run fgsea ---------------------------------------------------------------

# ranked_list <- scde_feature_list(shl_data)

ranked_list <- edger_feature_list(ks_data)

fgseaRes <- fgsea(pathways = examplePathways, 
									stats = ranked_list,
									minSize=15,
									maxSize=500,
									nperm=10000)

m_list = m_df %>% 
	split(x = .$gene_symbol, f = .$gs_name)

fgsea(pathways = m_list, ...)



clusterProfiler::enricher(gene = genes_entrez, TERM2GENE = m_t2g, ...)
```



