## Inspired/copied from https://github.com/snakemake-workflows/ngs-test-data/blob/master/.travis.yml
language: python
python:
  ## We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j8' > ~/.R/Makevars
  - echo 'options(Ncpus = 8)' > ~/.Rprofile
  - sudo apt-get install gfortran
  - sudo apt-get install libudunits2-dev

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  ## Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda create -q -n snakemake snakemake python=$TRAVIS_PYTHON_VERSION

script:
  - source activate snakemake
  ## run the workflow
  - travis_wait 50 snakemake --use-conda tximeta

## Print out the R log files
after_script:
  - tail example_data/output/Rout/install_pkgs.Rout
  - cat example_data/output/Rout/run_dge_edgeR.Rout
  