## Important note:
## All paths defined in this configuration file must be either absolute or relative to the
## location of the Snakefile!

proj_dir: ..

## Reference annotation details
##--------------------------------------------------------------------------------------------
## Specify "Ensembl" or "Gencode" depending on your choice
annotation: Ensembl

organism: Homo_sapiens # separate with underscore
build: GRCh38
release: 87
##--------------------------------------------------------------------------------------------

# read types
read_type: PE

## Paths to existing reference files
##--------------------------------------------------------------------------------------------
txome: /dataVolume/storage/Homo_sapiens/grch38/txome/Homo_sapiens.GRCh38.cdna.all.fa.gz
genome: /dataVolume/storage/Homo_sapiens/grch38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa
bed: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.bed
# standard
gtf: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.gtf
# retinal
# gtf: /dataVolume/storage/Homo_sapiens/grch38_tran_retinal_reference/Retina_Fetal.Tissue.gtf
repeat_mask: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.rmsk.gtf
samtools_mem: 3000
velocyto_threads: 4
dbtss_bed: /dataVolume/storage/Homo_sapiens/dbtss/corrected_dbtss.bed
chrom_sizes: /dataVolume/storage/Homo_sapiens/grch38/Homo_sapiens.GRCh38.dna_sm.primary_assembly.chrom.sizes
##--------------------------------------------------------------------------------------------

## Paths to indexes that will be generated by the workflow
##--------------------------------------------------------------------------------------------
salmonindex: /dataVolume/storage/Homo_sapiens/grch38/SalmonIndex/Homo_sapiens.GRCh38.9870.8.2
salmonk: 31
kallistoindex: /dataVolume/storage/Homo_sapiens/grch38/KallistoIndex/Homo_sapiens.kb.idx
kallistobatch: ../data/smart-seq_batch.txt
t2g: /dataVolume/storage/Homo_sapiens/grch38/KallistoIndex/t2g.txt
kallistok: 31
STARindex: /dataVolume/storage/Homo_sapiens/grch38_STAR_index
HISAT2index: /dataVolume/storage/Homo_sapiens/grch38_tran/genome_tran
##--------------------------------------------------------------------------------------------

## Information about the experiment
##--------------------------------------------------------------------------------------------
readlength: 75

## Mean and standard deviation of the fragment length distribution, for use with Salmon.
## This is important to specify for single-end reads.
## For paired-end reads, these values will define the prior, which is then updated
## based on the observed fragment lengths.
fldMean: 250
fldSD: 25

## Path to metadata text file. This file must contain at least the following columns:
## names: the sample identifiers = the names of the FASTQ files (excluding the _R1/R2.fastq.gz part)
## type: either SE or PE, indicating whether the sample was analyzed
## via single-end or paired-end sequencing.
metatsv: ../data/metadata.tsv

## Variables used for model fitting
## design: design formula for use with edgeR, camera and DRIMSeq. Must be a string
## of the form "~ <predictors>"
## contrast: (comma-separated if multiple) list of contrasts to estimate in edgeR_dge.Rmd
design: "~ 0 + celline"
contrast: cellineN61311-cellineN052611,cellineN052611-cellineN61311

## Gene sets used for gene set analysis with camera
## Comma-separated list of gene set categories to test with camera.
## Must be a subset of H,C1,C2,C3,C4,C5,C6,C7
## Only required if variable "run_camera: is True (see below).
genesets: H,C5

## The maximal number of cores to use for FastQC, STAR, Salmon and DRIMSeq.
## Note that the actual number of cores available to Snakemake is determined by
## the --cores argument when it is invoked.
ncores: 6
##---------------------------------------------------------------------------------------------


## Path to a folder containing gzipped fastq files, and the file suffix (typically, either fastq or fq).
## If you have paired-end fastq files, you also need to define the extension distinguishing the two read files.
## More precisely, ARMOR assumes that paired-end fastq files are named
## <sample-name>_<fqext1>.<fqsuffix>.gz and <sample-name>_<fqext2>.<fqsuffix>.gz.
## Single-end fastq files are supposed to be named
## <sample-name>.<fqsuffix>.gz.
##---------------------------------------------------------------------------------------------
FASTQ: ../data/FASTQ/
fqext1: 1
fqext2: 2
fqsuffix: fastq
##---------------------------------------------------------------------------------------------

## jbrowse setup
##---------------------------------------------------------------------------------------------
refdir: /dataVolume/storage/Homo_sapiens
gff: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.sorted.gff3.gz
gff_tbi: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.sorted.gff3.gz.tbi
refseq: /dataVolume/storage/Homo_sapiens/grch38_tran/refSeqs.json
##---------------------------------------------------------------------------------------------

## Path to a folder that will store the output generated by the workflow.
## Additional subfolders of this folder will be generated by the workflow.
## To put output in the current directory, set output to ".".
##---------------------------------------------------------------------------------------------
output: ../output/
##---------------------------------------------------------------------------------------------

## R setup
##---------------------------------------------------------------------------------------------
## Specify "True" if R should be installed in a conda environment or "False" if you want to use
## your own R installation (then you have to set the path to your library in the .Renviron file)
useCondaR: False
Rbin: "/usr/bin/R"
##---------------------------------------------------------------------------------------------

## Scenic
TFs: /dataVolume/storage/Homo_sapiens/scenic/hs_hgnc_curated_tfs.txt
motifs: /dataVolume/storage/Homo_sapiens/scenic/motifs-v9-nr.hgnc.tbl
feather_db: /dataVolume/storage/Homo_sapiens/scenic/hg38_refseq-10kb_up_and_down_tss.mc9nr.feather

# cellranger
cellranger_transcriptome: /dataVolume/storage/Homo_sapiens/cellranger/refdata-gex-GRCh38-2020-A

## DEXSeq
roi_bed: ../output/dexseq/genes_of_interest.bed
exon_collapsed_gff: /dataVolume/storage/Homo_sapiens/grch38_tran/Homo_sapiens.GRCh38.87.dexseq.gtf

## scTE
te_build: hg38
te_index: /dataVolume/storage/Homo_sapiens/grch38/hdg38.exclusive.idx

## numbat
gmap: /usr/local/bin/TOOLS/Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz
snpvcf: /dataVolume/storage/Homo_sapiens/numbat/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf.gz
paneldir: /dataVolume/storage/Homo_sapiens/numbat/1000G_hg38
max_entropy: 0.5
min_LLR: 2
max_iter: 2
read_prop: 1
tau: 0.3
numbat_t: 1e-5
cell_ceiling: 1e4
gamma: 30
wu_ref_path: /dataVolume/storage/Homo_sapiens/numbat/wu_ref.rds
yang_ref_path: /dataVolume/storage/Homo_sapiens/numbat/yang_ref.rds
field_ref_path: /dataVolume/storage/Homo_sapiens/numbat/field_ref.rds
collin_ref_path: /dataVolume/storage/Homo_sapiens/numbat/collin_ref.rds
sridhar_ref_path: /dataVolume/storage/Homo_sapiens/numbat/sridhar_ref.rds
sridhar_cone_ref_path: /dataVolume/storage/Homo_sapiens/numbat/sridhar_cone_ref.rds

## seurat
celltype_ref: /dataVolume/storage/Homo_sapiens/numbat/plae_ref.rds

## infercnv
normal_reference_mat: /dataVolume/storage/Homo_sapiens/infercnv/reference_mat.rds

## Conditional conda rules
##---------------------------------------------------------------------------------------------
## Should read trimming, STAR mapping, DRIMSeq analysis and gene set analysis be performed? Set
## to False if the step is not required.
run_trimming: False
run_STAR: False
run_HISAT2: False
run_SALMON: False
run_DRIMSeq: False
run_camera: False
run_genebodycoverage: False
##---------------------------------------------------------------------------------------------
