library(readxl)
library(dplyr)
library(tidyr)
library(base)
library(reshape2)
getwd()
xl_table <- read_excel('single_cell_pipeline/src/022618_Hier_9cluster.xlsx')
t_xl <- t(xl_table)
t_xl_df <- as.data.frame(t_xl)
colnames(t_xl_df) <- unlist(t_xl_df[2,])
t_xl_df <- t_xl_df[-c(1:2),]
cell_id_table <- gather(data = t_xl_df, key = "cluster", value ="Sample_ID", na.rm = TRUE)
merged_df <- dplyr::left_join(cell_id_table, cell_info, by=("Sample_ID"))
write.table(merged_df, '~/single_cell_pipeline/output/merged_analyses/peleg_dominic_df.csv', sep="\t")
analysis1 <- dplyr::mutate(merged_df,analysis1=ifelse(merged_df[,1]==0 | merged_df[,1] ==2, "1", ifelse(merged_df[,1]==4,"2",NA)))
analysis1 <- analysis1[,c(2,1,3:length(analysis1))]
