channels:
- bioconda
- conda-forge
dependencies:
- kallisto=0.46.2
- samtools=1.9
- salmon=0.10.2
- star=2.7.5a
- fastqc=0.11.7
- multiqc=1.6a0
- trim-galore=0.5.0
- cutadapt=1.16
- bedtools=2.27.1
- ucsc-bedgraphtobigwig=366
- pandoc
- pandas
- cython
- numba
- HTSeq=0.12.4
- pip
- pip:
    - velocyto
